name: build
on:
    push:
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 17
                  cache: npm
            - run: npm install
            - run: npm run lint
            - run: npm run check
            - run: npm run build
